### ISSUE TITLE
Proj support

### ISSUE THREAD

**Issue by sokrat** [garrettrayj/php7-mapnik#11]
Hi
When I call ```ProjTransform->backward()``` or ```ProjTransform->forward()``` with any projection different from 4326 and 3857 i get segmentation fault.
Mapnik compiled from source with proj4 support, tested on debian and alpine.
example:
```
$boundingBox = new Box2D($minX, $minY, $maxX, $maxY);
$source = new Projection('+init=epsg:4326');
$destination = new Projection('+init=epsg:32638');
$transform = new ProjTransform($source, $destination);
$tileBoundingBox = $transform->backward($boundingBox);
```

**Comment by garrettrayj** [comment]
Thank you for reporting! [1.2.2](https://github.com/garrettrayj/php7-mapnik/releases/tag/1.2.2) includes the fix.
