### ISSUE TITLE
make test fails on imagecreatefromstring()

### ISSUE THREAD

**Issue by 3XE** [garrettrayj/php7-mapnik#5]
Not sure what is going on here but cannot complete the installation steps because `make test` fails on  imagecreatefromstring() image.phpt.

Naturally, the first thing I checked is the presence of gd and it was present.  Next I copied the [imagecreatefromstring() example](http://php.net/manual/en/function.imagecreatefromstring.php#example-3515) from the PHP docs into a regular .php file and, oddly enough, it works as expected.

[php_test_results_20160416_1939.txt](https://github.com/garrettrayj/php7-mapnik/files/222394/php_test_results_20160416_1939.txt)

Most strange :S

-Peter

**Comment by 3XE** [comment]
I have dug into this further, I think the issue has got to be GD not being loaded by tmp-php.ini for some reason because if I enable the extension anyway and run the tests manually it works fine.  I thought it might be something to do with using the PHP CLI but the `imagecreatefromstring()` example above works fine using the CLI.

**Comment by garrettrayj** [comment]
Thanks for reporting! You were spot on, the tmp-php.ini was leaving GD out.
