### ISSUE TITLE
render bounding box question

### ISSUE THREAD

**Issue by africanrhino** [garrettrayj/php7-mapnik#8]
is there any way we can get the bbox and scale of what is to be rendered by the map? the zoomToBox zooms the image to fit the bounds of map, but if say you produce a 800X600 image based on a zoomToBox that's 16:9 then the rendered bounding box will be significantly different to the original 16:9. I'm trying to manipulate the data layer to exclude any label on the edge of the map but without knowing what the true bounding box is and without knowing the scale will be makes this difficult. any ideas here?

**Comment by garrettrayj** [comment]
Mapnik has functionality to get a map's extent and scale, but it is not implemented in the extension yet. I also suspect that being able to change the _aspect fix mode_ (https://github.com/mapnik/mapnik/wiki/Aspect-Fix-Mode) would be helpful.

Relevant Mapnik methods:
- get_current_extent (https://github.com/mapnik/mapnik/blob/master/include/mapnik/map.hpp#L413)
- get_buffered_extent (https://github.com/mapnik/mapnik/blob/master/include/mapnik/map.hpp#L418)
- scale (https://github.com/mapnik/mapnik/blob/master/include/mapnik/map.hpp#L423)
- scale_denominator (https://github.com/mapnik/mapnik/blob/master/include/mapnik/map.hpp#L425)
- set_aspect_fix_mode (https://github.com/mapnik/mapnik/blob/master/include/mapnik/map.hpp#L457)

Let me know if you want to tackle implementation. Otherwise I'll work up something over the next week or two.

**Comment by africanrhino** [comment]
I wish I could. not very handy with c. I am at "hello world" level. I think those mapnik methods would be very handy. am trying to implement it via the !bbox! intersect thing but its not very flexible nor particularly useful.  perusing the map.hpp, remove_style might also be very useful in the long run. I suspect this project will mostly be used to generate static maps, at least that's how i'm using it and managing layers and styles is big one for that. the way i am doing it is loading the xml file and altering the style and layer then send it via loadXmlString(). 

great project, very useful to have this available native in php7+ thank you very much for the effort so far!

**Comment by garrettrayj** [comment]
The discussed methods are now available in the _develop_ branch. There is some house keeping and documentation work I want to get in, so a tagged release is still a couple weeks out. Until then, the [map class tests](https://github.com/garrettrayj/php7-mapnik/blob/develop/tests/map.phpt) offer the best look into what's available.

**Comment by africanrhino** [comment]
great enhancements , good to see you pulled though a lot more than i thought you were. I've tried to compile it but it to be failing on
> make test
> @ FAIL \Mapnik\Image [tests/image.phpt]

i didn't get any compile errors. could it be a libgd version thing? the master branch still compiles and passes the tests.

**Comment by garrettrayj** [comment]
Paths for test images were missing a directory separator. 🤦‍♂️

I got Travis (Ubuntu Trusty) back to building successfully so you might pull and try again. Thanks!

**Comment by africanrhino** [comment]
ok , all is working , new functions are sweet! :) 

$class_methods = get_class_methods($map);
echo print_r($class_methods,true);
gives -> 

Array
(
    [0] => __construct
    [1] => loadXmlFile
    [2] => loadXmlString
    [3] => zoom
    [4] => zoomAll
    [5] => pan
    [6] => panAndZoom
    [7] => zoomToBox
    [8] => registerFonts
    [9] => getBasePath
    [10] => setBasePath
    [11] => getWidth
    [12] => setWidth
    [13] => getHeight
    [14] => setHeight
    [15] => resize
    [16] => getSrs
    [17] => setSrs
    [18] => getBackgroundImage
    [19] => setBackgroundImage
    [20] => getBackgroundImageOpacity
    [21] => setBackgroundImageOpacity
    [22] => getMaximumExtent
    [23] => setMaximumExtent
    [24] => resetMaximumExtent
    [25] => getCurrentExtent
    [26] => getBufferSize
    [27] => setBufferSize
    [28] => getBufferedExtent
    [29] => getScale
    [30] => getScaleDenominator
    [31] => countLayers
    [32] => removeStyle
    [33] => removeAll
    [34] => getAspectFixMode
    [35] => setAspectFixMode
)

**Comment by garrettrayj** [comment]
New functionality has been merged into master and released with 1.2.0. Make sure and checkout the new API docs too. Thank you for creating the issue!
